### PR TITLE
Adds plugin profile.js to allow preparing JBrowse release

### PR DESCRIPTION
**Pull request by vivekkrish**
Hi @bhofmei , 
Thank you for developing this (and other useful) JBrowse plugins! This PR corrects a minor syntax error in the main.js as well as adds a profile.js for this plugin, so that when a `make build/Makefile release` is run in the JBrowse directory, the plugin code is successfully parsed and minified.

Please review this PR and accept at your convenience.

Thank you!

### CODE REVIEW

**Comment by bhofmei** [comment]
Awesome! Thank you.
I’m pretty new to javascript and noticed minifying but wasn’t quite sure how to do it. There’s also quite a few other plugins on my to-do list, so minifying wasn’t my top priority as long as the plugin worked. On that note, I know this plugin has a few bugs (not functional, just annoying for the perfectionist in me) that I haven’t gotten around to fixing.
Please feel free to spread the word about my plugins!

Brigitte

**Comment by vivekkrish** [comment]
Absolutely! I've already told my teammates/colleagues about your smallRNA plugin as well as the one which can dynamically adjust Y-scale.

From our use of your plugin, it seems to be working well. Here is a our JBrowse instance using the checkbox plugin: https://apps.araport.org/jbrowse/?data=arabidopsis (implemented as part of the Arabidopsis Information Portal project, https://www.araport.org).

When we get around to using your other plugins in our production JBrowse instance, I hope to send in some more pull requests to help with the code minification (we've done this for [all plugins written by us](https://github.com/Arabidopsis-Information-Portal/jbrowse/tree/stable/plugins)).

I would recommend sending an email on the [JBrowse mailing list](https://lists.sourceforge.net/lists/listinfo/gmod-ajax), and tell everyone about these awesome plugins, so that you can gain some valuable feedback from the JBrowse community of developers.

Thanks again for these plugins!

Regards,
Vivek

**Comment by bhofmei** [comment]
That’s a good idea. Thanks!
As part of my PhD, I’m planning on publishing the plugins as a suite by the end of the year, once I develop 2 more key plugins. I just haven’t been sure to balance spreading the word vs. risk getting scooped, so I’ve stayed relatively quiet until now. I know, I need to add licensing information to all the plugins. Until now I didn’t realize anyone else was actually using them!
Brigitte

**Comment by vivekkrish** [comment]
Oh, that's great. Good luck with your PhD work!

We came across your plugins by a search through GitHub for open source development that others were doing in this space. We probably should have asked you first before using it ;)

Thank you so much for accepting the PR.

Regards,
Vivek

**Pull request merged**
